### ISSUE TITLE
Kreiranje SRS dokument-a

### ISSUE THREAD

**Issue by TajmaMahmutovicETF** [RPR-2019/POSkasa#1]
Šta treba sadržavati:
- [x] Naslovna strana
- [x] Sadržaj
- [x] Historija revizija
1. Uvod
- [x]  1.1. Svrha dokumenta
- [x]  1.2. Opseg (scope) dokumenta
- [x]  1.3. Standardi dokumentovanja
- [x]  1.4. Akronimi i definicije
- [x]  1.5. Reference
2. Opis
- [x]  2.1. Perspektiva proizvoda
- [x]  2.2. Funkcionalnosti proizvoda
- [x]  2.3. Karakteristike korisnika
- [x]  2.4. Ograničenja - Zakonska regulativa.
- [x]  2.5. Pretpostavke i zavisnosti
- [x]  2.6. Planiranje zahtjeva
3. Konkretni zahtjevi
- [x]  3.1. Vanjski interfejsi
- [x]  3.2. Funkcionalni zahtjevi
- [x]  3.3. Nefunkcionalni zahtjevi
- [x]  3.4. Atributi kvalitete softvera
- [x] Prilozi

**Comment by apozegija1** [comment]
[SRS-POS-kasa.pdf](https://github.com/RPR-2019/POSkasa/files/4444091/SRS-POS-kasa.pdf)
