### ISSUE TITLE
Kreirati dijagram entitet-veza

### ISSUE THREAD

**Issue by apozegija1** [RPR-2019/POSkasa#3]
Entity-Relationship Modelling
Kreirati detaljan logički prikaz podataka preko skupa
entiteta, njihovih atributa i međusobnih veza.

Osnovni elementi modela su:
- entiteti (objekti),
- veze,
- atributi.

**Comment by apozegija1** [comment]
@SuperRsDev

**Comment by SuperRsDev** [comment]
Prva verzija ERD za POS sistem
https://drive.google.com/file/d/1eBysSOq2pBL7XmJqkUoiyOOzkI-BFlPt/view?usp=sharing

**Comment by SuperRsDev** [comment]
ERD za POS sistem
https://drive.google.com/file/d/1GYFBJkIV0ixG9hmEnQj3lM38LXRsF_HT/view?usp=sharing
