### ISSUE TITLE
Kreirati dijagram raspoređivanja

### ISSUE THREAD

**Issue by apozegija1** [RPR-2019/POSkasa#5]
Ovim dijagramom se modeliraju hardverski resursi (stvarni ili virtuelni), veze između njih 
(komunikacijski protokoli i konekcije) i način raspoređivanja softvera na te resurse.

Primjer: [https://c2.etf.unsa.ba/pluginfile.php/16989/mod_resource/content/0/ooad2010-predavanja/Knjiga.pdf](url)
**str. br. 281 i 282**

**Comment by apozegija1** [comment]
@fluks4

**Comment by fluks4** [comment]
Novi dijagram 

![dijagram rasporedjivanja 2](https://user-images.githubusercontent.com/48660017/81146892-7aaa0900-8f79-11ea-8721-a2ea55b87b1e.png)
