### ISSUE TITLE
Kreirati dijagram komponenti

### ISSUE THREAD

**Issue by apozegija1** [RPR-2019/POSkasa#6]
Dijagram komponenti je pogled visokog nivoa koji opisuje arhitekturu sistema. 
Primjer: [https://c2.etf.unsa.ba/pluginfile.php/16989/mod_resource/content/0/ooad2010-predavanja/Knjiga.pdf](url)
**str.br 254** - pogledati čitavo poglavlje!

**Comment by apozegija1** [comment]
@fluks4

**Comment by apozegija1** [comment]
@fluks4 Možeš li ovdje isto postaviti slike dijagrama komponenti molim te, pa ćemo ih objediniti u dokument "Dizajn sistema" kada svi završe svoj dio 😃 

*i za dijagrame raspoređivanja isto

**Comment by fluks4** [comment]
![DijagramKomponentiWeb](https://user-images.githubusercontent.com/48660017/79641746-b97a4980-8199-11ea-94ec-c539ef9a1f09.png)
![DijagramKomponentiDesktop (1)](https://user-images.githubusercontent.com/48660017/79641747-ba12e000-8199-11ea-8e30-3b7635fddaac.png)

Evo ga :)
